indenting

diff --git a/bash_prompt b/bash_prompt
--- a/bash_prompt
+++ b/bash_prompt
@@ -24,60 +24,60 @@ unset __colourise_prompt && __colour_enabled && __colourise_prompt=1
 
 __set_bash_prompt()
 {
-    local exit="$?" # Save the exit status of the last command
+  local exit="$?" # Save the exit status of the last command
 
-    # PS1 is made from $PreGitPS1 + <git-status> + $PostGitPS1
-    local PreGitPS1="\n${debian_chroot:+($debian_chroot)}"
-    local PostGitPS1=""
+  # PS1 is made from $PreGitPS1 + <git-status> + $PostGitPS1
+  local PreGitPS1="\n${debian_chroot:+($debian_chroot)}"
+  local PostGitPS1=""
 
-    if [[ $__colourise_prompt ]]; then
-        export GIT_PS1_SHOWCOLORHINTS=1
+  if [[ $__colourise_prompt ]]; then
+    export GIT_PS1_SHOWCOLORHINTS=1
 
-        # Wrap the colour codes between \[ and \], so that
-        # bash counts the correct number of characters for line wrapping:
-        local Red='\[\e[0;31m\]'; local BRed='\[\e[1;31m\]'
-        local Gre='\[\e[0;32m\]'; local BGre='\[\e[1;32m\]'
-        local Yel='\[\e[0;33m\]'; local BYel='\[\e[1;33m\]'
-        local Blu='\[\e[0;34m\]'; local BBlu='\[\e[1;34m\]'
-        local Mag='\[\e[0;35m\]'; local BMag='\[\e[1;35m\]'
-        local Cya='\[\e[0;36m\]'; local BCya='\[\e[1;36m\]'
-        local Whi='\[\e[0;37m\]'; local BWhi='\[\e[1;37m\]'
-        local None='\[\e[0m\]' # Return to default colour
+    # Wrap the colour codes between \[ and \], so that
+    # bash counts the correct number of characters for line wrapping:
+    local Red='\[\e[0;31m\]'; local BRed='\[\e[1;31m\]'
+    local Gre='\[\e[0;32m\]'; local BGre='\[\e[1;32m\]'
+    local Yel='\[\e[0;33m\]'; local BYel='\[\e[1;33m\]'
+    local Blu='\[\e[0;34m\]'; local BBlu='\[\e[1;34m\]'
+    local Mag='\[\e[0;35m\]'; local BMag='\[\e[1;35m\]'
+    local Cya='\[\e[0;36m\]'; local BCya='\[\e[1;36m\]'
+    local Whi='\[\e[0;37m\]'; local BWhi='\[\e[1;37m\]'
+    local None='\[\e[0m\]' # Return to default colour
 
-        # No username and bright colour if root
-        if [[ ${EUID} == 0 ]]; then
-            PreGitPS1+="$BRed\h "
-        else
-            PreGitPS1+="$Gre\u@\h$None:"
-        fi
-
-        PreGitPS1+="$Blu\w$None "
-    else # No colour
-        # Sets prompt like: user@box:~/dir/file
-        unset GIT_PS1_SHOWCOLORHINTS
-        PreGitPS1="${debian_chroot:+($debian_chroot)}\u@\h:\w"
-    fi
-
-    # Now build the part after git's status
-
-    # Highlight non-standard exit codes
-    if [[ $exit != 0 ]]; then
-        PostGitPS1="$Red[$exit]"
-    fi
-
-    # Change colour of prompt if root
+    # No username and bright colour if root
     if [[ ${EUID} == 0 ]]; then
-        PostGitPS1+="\n""$BRed"'\$ '"$None"
+      PreGitPS1+="$BRed\h "
     else
-        PostGitPS1+="\n""$Mag"'\$ '"$None"
+      PreGitPS1+="$Gre\u@\h$None:"
     fi
 
-    # Set PS1 from $PreGitPS1 + <git-status> + $PostGitPS1
-    __git_ps1 "$PreGitPS1" "$PostGitPS1" '(%s) '
+    PreGitPS1+="$Blu\w$None "
+  else # No colour
+    # Sets prompt like: user@box:~/dir/file
+    unset GIT_PS1_SHOWCOLORHINTS
+    PreGitPS1="${debian_chroot:+($debian_chroot)}\u@\h:\w"
+  fi
 
-    # echo '$PS1='"$PS1" # debug    
-    # defaut Linux Mint 17.2 user prompt:
-    # PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[01;34m\] \w\[\033[00m\] $(__git_ps1 "(%s)") \$ '
+  # Now build the part after git's status
+
+  # Highlight non-standard exit codes
+  if [[ $exit != 0 ]]; then
+    PostGitPS1="$Red[$exit]"
+  fi
+
+  # Change colour of prompt if root
+  if [[ ${EUID} == 0 ]]; then
+    PostGitPS1+="\n""$BRed"'\$ '"$None"
+  else
+    PostGitPS1+="\n""$Mag"'\$ '"$None"
+  fi
+
+  # Set PS1 from $PreGitPS1 + <git-status> + $PostGitPS1
+  __git_ps1 "$PreGitPS1" "$PostGitPS1" '(%s) '
+
+  # echo '$PS1='"$PS1" # debug    
+  # defaut Linux Mint 17.2 user prompt:
+  # PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[01;34m\] \w\[\033[00m\] $(__git_ps1 "(%s)") \$ '
 }
 
 # This tells bash to reinterpret PS1 after every command, which we
